version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      SECRET_KEY: "mysecretkey"
      SQLALCHEMY_DATABASE_URI: "mssql+pyodbc://sa:SecureP@ssw0rd123@db/PhotoSphere?driver=ODBC+Driver+18+for+SQL+Server"
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SecureP@ssw0rd123"
      ACCEPT_EULA: "Y"
